# Generated by Django 3.1.3 on 2020-11-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201113_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/img', verbose_name='Картинка'),
        ),
    ]
